#!/bin/bash
# Morning Brief — macOS Automation Installer
# Installs a launchd agent that runs your morning brief at 7:30 AM on weekdays.
#
# Usage: bash automation/install-macos.sh

set -e

USER_HOME="$HOME"
SCRIPTS_DIR="$USER_HOME/scripts"
LOGS_DIR="$USER_HOME/Library/Logs"
LAUNCH_AGENTS_DIR="$USER_HOME/Library/LaunchAgents"
PLIST_LABEL="com.morningbrief"
PLIST_PATH="$LAUNCH_AGENTS_DIR/$PLIST_LABEL.plist"
SCRIPT_PATH="$SCRIPTS_DIR/run-morning-brief.sh"

echo ""
echo "Morning Brief — macOS Installer"
echo "================================"
echo ""

# ── Find claude binary ──────────────────────────────────────────────────────
CLAUDE_BASE="$USER_HOME/Library/Application Support/Claude/claude-code"
CLAUDE_BIN=$(find "$CLAUDE_BASE" -maxdepth 2 -name "claude" -type f 2>/dev/null | sort -V | tail -1)

if [ -z "$CLAUDE_BIN" ]; then
  echo "❌  Claude binary not found."
  echo "    Install Claude Code first: https://claude.ai/code"
  exit 1
fi

echo "✅  Found Claude at: $CLAUDE_BIN"

# ── Create scripts and logs dirs ────────────────────────────────────────────
mkdir -p "$SCRIPTS_DIR" "$LOGS_DIR" "$LAUNCH_AGENTS_DIR"

# ── Write run script ────────────────────────────────────────────────────────
cat > "$SCRIPT_PATH" << SCRIPT_EOF
#!/bin/bash
# Morning Brief Runner (generated by install-macos.sh)

LOG="$LOGS_DIR/morning-brief.log"

# Skip weekends
DAY=\$(date +%u)
if [ "\$DAY" -ge 6 ]; then
  echo "\$(date '+%Y-%m-%d %H:%M'): Weekend — skipping." >> "\$LOG"
  exit 0
fi

# Find latest claude binary (handles version updates automatically)
CLAUDE_BASE="$USER_HOME/Library/Application Support/Claude/claude-code"
CLAUDE=\$(find "\$CLAUDE_BASE" -maxdepth 2 -name "claude" -type f 2>/dev/null | sort -V | tail -1)

if [ -z "\$CLAUDE" ]; then
  echo "\$(date '+%Y-%m-%d %H:%M'): ERROR — Claude binary not found" >> "\$LOG"
  exit 1
fi

echo "\$(date '+%Y-%m-%d %H:%M'): Starting morning brief..." >> "\$LOG"
"\$CLAUDE" -p "/morning-brief" >> "\$LOG" 2>&1

TODAY=\$(date +%Y-%m-%d)
BRIEF="\$HOME/Desktop/morning-brief-\${TODAY}.html"
if [ -f "\$BRIEF" ]; then
  open "\$BRIEF"
fi

echo "\$(date '+%Y-%m-%d %H:%M'): Done." >> "\$LOG"
SCRIPT_EOF

chmod +x "$SCRIPT_PATH"
echo "✅  Created runner script at: $SCRIPT_PATH"

# ── Write launchd plist ─────────────────────────────────────────────────────
cat > "$PLIST_PATH" << PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$PLIST_LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$SCRIPT_PATH</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Hour</key>
    <integer>7</integer>
    <key>Minute</key>
    <integer>30</integer>
  </dict>
  <key>StandardOutPath</key>
  <string>$LOGS_DIR/morning-brief.log</string>
  <key>StandardErrorPath</key>
  <string>$LOGS_DIR/morning-brief-error.log</string>
  <key>RunAtLoad</key>
  <false/>
</dict>
</plist>
PLIST_EOF

echo "✅  Created launchd plist at: $PLIST_PATH"

# ── Load the agent ──────────────────────────────────────────────────────────
# Unload first in case it was already loaded
launchctl unload "$PLIST_PATH" 2>/dev/null || true
launchctl load "$PLIST_PATH"

echo "✅  Launchd agent loaded and scheduled"
echo ""
echo "┌─────────────────────────────────────────────────────┐"
echo "│  Morning Brief will run at 7:30 AM on weekdays.    │"
echo "│                                                     │"
echo "│  To change the time, edit:                         │"
echo "│  ~/Library/LaunchAgents/com.morningbrief.plist     │"
echo "│  (Hour and Minute keys)                            │"
echo "│                                                     │"
echo "│  To test it now:                                   │"
echo "│  bash ~/scripts/run-morning-brief.sh               │"
echo "│                                                     │"
echo "│  To view logs:                                     │"
echo "│  tail -f ~/Library/Logs/morning-brief.log          │"
echo "│                                                     │"
echo "│  To uninstall:                                     │"
echo "│  launchctl unload ~/Library/LaunchAgents/com.morningbrief.plist │"
echo "└─────────────────────────────────────────────────────┘"
echo ""
